### ISSUE TITLE
Vendor-agnostic names

### ISSUE THREAD

**Issue by louismullie** [coda-platform/site-deployer-ansible#11]
Hi team, 

With the latest version of the code, we have tried to move away from vendor-specific naming schemes in all the configuration variables and deployment scripts. This will facilitate things if/when we want to swap parts of the architecture to different vendors and prevent naming schemes from becoming stale.

Would it be reasonable to harmonize the naming schemes in the playbooks with the names of the repositories?

- coda_aidbox -> coda_fhir_store
- coda_orthanc -> coda_dicom_store
- coda_redis -> coda_cache_db

And so on.

**Comment by JulienL3vesque** [comment]
Good point will check with @fmarois

**Comment by JulienL3vesque** [comment]
minio -> coda_object_storage

**Comment by fmarois** [comment]
Changed the name of the ansible roles to vendor agnostic names.
